### ISSUE TITLE
Test suite does not build from Hackage

### ISSUE THREAD

**Issue by snoyberg** [guillaume-nargeot/hpc-coveralls#34]
Likely files missing in the sdist tarball:

```
Resolving dependencies...
Configuring hpc-coveralls-0.8.0...
Building hpc-coveralls-0.8.0...
Preprocessing library hpc-coveralls-0.8.0...
In-place registering hpc-coveralls-0.8.0...
Preprocessing executable 'hpc-coveralls' for hpc-coveralls-0.8.0...
Preprocessing executable 'run-cabal-test' for hpc-coveralls-0.8.0...
Preprocessing test suite 'test-all' for hpc-coveralls-0.8.0...

test/TestAll.hs:5:8:
    Could not find module ‘TestHpcCoverallsLix’
    Use -v to see a list of the files searched for.

test/TestAll.hs:6:8:
    Could not find module ‘TestHpcCoverallsUtil’
    Use -v to see a list of the files searched for.
```

I added hpc-coveralls to Stackage recently, as I used it for mutable-containers and found it incredibly convenient. Thank you!

**Comment by guillaume-nargeot** [comment]
Thank you very much for adding it to stackage, I was not really sure of the exact procedure.
Is there something I should do regarding the lower/upper bounds of the dependencies I use?
I'm still not sure of what is the best practice regarding this. Is there some recommended reading?

Regarding the issue with TestHpcCoverallsLix and TestHpcCoverallsUtil not being included, I'm going to fix this and will tell you once done.

**Comment by snoyberg** [comment]
If there are any issues in the future I'll let you know. Add it stands the
package seems to be in great shape.
