### ISSUE TITLE
Travis Pro

### ISSUE THREAD

**Issue by msakai** [guillaume-nargeot/hpc-coveralls#49]
I just tried hpc-coveralls with Travis Pro, and noticed that it is necessary to specify "travis-pro" as a service name for coveralls.io to retrive build information correctly.

As a quick fix, I added a command line option to explicitly specify service name, because I couldn't find a way to distinguish travis-pro from normal travis-ci.
https://github.com/msakai/hpc-coveralls/commit/2bec43f1242b184f615c1651e5f67b78b8ee0802

**Comment by guillaume-nargeot** [comment]
Sorry for the delay in getting back to you. I am not really familiar with Travis Pro, I'll check if there is another way, and will merge your fix if not.
Thanks

**Comment by guillaume-nargeot** [comment]
I've pulled your changes to https://github.com/guillaume-nargeot/hpc-coveralls/tree/travis-pro-support and merged them to https://github.com/guillaume-nargeot/hpc-coveralls/tree/develop.
This should go in the next version to be release (1.0.0).
Thank you very much for your contribution!

**Comment by guillaume-nargeot** [comment]
Doc: when using travis pro, add the following option to the `hpc-coveralls` command: `--service-name travis-pro`
