### ISSUE TITLE
Linker errors with --enable-executable-dynamic

### ISSUE THREAD

**Issue by peti** [guillaume-nargeot/hpc-coveralls#52]
Citing from http://hydra.cryp.to/build/1199867/nixlog/1/raw:

~~~
Linking dist/build/test-all/test-all ...
/tmp/nix-build-hpc-coveralls-0.9.0.drv-0/hpc-coveralls-0.9.0/dist/build/libHShpc-coveralls-0.9.0-6Q8vPLE5qvd6iS3fdA3Ztx-ghc7.10.2.so: undefined reference to `hpccozu6Q8vPLE5qvd6iS3fdA3ZZtx_Pathszuhpczucoveralls_version1_closure'
collect2: error: ld returned 1 exit status
~~~

This error goes away when I remove `--enable-executable-dynamic` from the set of configure flags.

**Comment by guillaume-nargeot** [comment]
I'm not really familiar with the linker, this error and the flag you mention, but I will have a look.
Is the issue only occurring for a certain version of GHC or for all versions?
BY the way, GHC 7.10 is now supported in hpc coveralls latest version (1.0.1)

**Comment by RyanGlScott** [comment]
#59 fixes this.
