### ISSUE TITLE
Not in scope: '<>'

### ISSUE THREAD

**Issue by maoe** [guillaume-nargeot/hpc-coveralls#54]
I got this error today:
https://travis-ci.org/maoe/lifted-async/jobs/91491741#L444

I haven't checked yet but I guess this is because `retry` now doesn't re-export `<>`.

FWIW, this issue could have been avoided if there were upper bounds specified in the cabal file. What do you think?

**Comment by guillaume-nargeot** [comment]
Fixed by #55
