### ISSUE TITLE
Support retry 0.7

### ISSUE THREAD

**Issue by DanBurton** [guillaume-nargeot/hpc-coveralls#56]
#54 was apparently fixed by adding an upper bound on the `retry` package. This issue is a request to support building against the new version of `retry`.

See also: https://github.com/fpco/stackage/issues/975

**Comment by guillaume-nargeot** [comment]
Ok, will do as soon as possible

**Comment by guillaume-nargeot** [comment]
Fixed by #55

**Comment by DanBurton** [comment]
Sweet, thanks!
